name: Python
on:
  schedule:
  - cron: "*/10 * * * *"
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner.
        - name: setup python
          uses: actions/setup-python@v2
          with:
              python-version: 3.10.2 #install the python needed
        - name: execute py script # run the run.py to get the latest data
          run: |
              python Levi.py
              
        - name: commit files
          run: |
                git config --local user.email "machlevi2021@gmail.com"
                git config --local user.name "Mach-Levi"
                git add -A
                git commit -m "update data" -a
        
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main